// <auto-generated />
using System;
using Emigrante.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emigrante.App.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211129050939_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Emigrante.App.Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MigranteId")
                        .HasColumnType("int");

                    b.Property<string>("Relacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MigranteId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Cupos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MigranteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("MigranteId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Entidad", b =>
                {
                    b.HasBaseType("Emigrante.App.Dominio.Persona");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Entidad");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Migrante", b =>
                {
                    b.HasBaseType("Emigrante.App.Dominio.Persona");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("Situacionlaboral")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EntidadId");

                    b.HasDiscriminator().HasValue("Migrante");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.UsuarioGerencia", b =>
                {
                    b.HasBaseType("Emigrante.App.Dominio.Persona");

                    b.Property<string>("Dependencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsuarioGerencia");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Grupo", b =>
                {
                    b.HasOne("Emigrante.App.Dominio.Migrante", "Migrante")
                        .WithMany()
                        .HasForeignKey("MigranteId");

                    b.Navigation("Migrante");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Servicio", b =>
                {
                    b.HasOne("Emigrante.App.Dominio.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId");

                    b.HasOne("Emigrante.App.Dominio.Migrante", "Migrante")
                        .WithMany()
                        .HasForeignKey("MigranteId");

                    b.Navigation("Entidad");

                    b.Navigation("Migrante");
                });

            modelBuilder.Entity("Emigrante.App.Dominio.Migrante", b =>
                {
                    b.HasOne("Emigrante.App.Dominio.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId");

                    b.Navigation("Entidad");
                });
#pragma warning restore 612, 618
        }
    }
}
